server:
   port: 8002
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    cache: false  # 此处为不缓存页面
 
mybatis:
  mapper-locations: classpath:yt/cn/test/mapping/*.xml
  type-aliases-package: yt.cn.test.pojo
